name: Revert PR auto-approve

on:
  pull_request:
    branches:
      - 'master'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: log
        env:
          PR: ${{ github.pull_request}}
          TITLE: ${{ github.pull_request.title }}
          REF: ${{ github.head_ref }}
        run: echo "$PR $TITLE $REF"
      - uses: hmarr/auto-approve-action@v2.0.0
        if: startsWith(github.head_ref, 'revert-') && startsWith(github.pull_request.title, 'Revert' )
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
