name: Revert PR auto-approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.pull_request.title.contains('revert')
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
