name: Revert PR auto-approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: contains('revert', github.pull_request.title) && startsWith(github.ref, '/refs/heads/revert-')
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
